import java.math.BigDecimal;
import java.util.*;

class Station { int id; String code,name; Station(int id,String code,String name){this.id=id;this.code=code;this.name=name;} }
class Passenger { int id; String name,phone,email; Passenger(int id,String name,String phone,String email){this.id=id;this.name=name;this.phone=phone;this.email=email;} }
class Seat { int id,number; String coach,cls; Seat(int id,String coach,int number,String cls){this.id=id;this.coach=coach;this.number=number;this.cls=cls;} }
class Stop { int stationId,distance; String arrival,departure; Stop(int stationId,String arrival,String departure,int distance){this.stationId=stationId;this.arrival=arrival;this.departure=departure;this.distance=distance;} }
class Train { int number; String name; List<Stop> stops=new ArrayList<>(); List<Seat> seats=new ArrayList<>(); Train(int number,String name){this.number=number;this.name=name;} void addStop(Stop s){stops.add(s);} int stopIndex(int station){for(int i=0;i<stops.size();i++)if(stops.get(i).stationId==station)return i;return -1;} boolean hasRoute(int s,int d){int a=stopIndex(s),b=stopIndex(d);return a>=0&&b>=0&&a<b;} int distance(int s,int d){if(!hasRoute(s,d))return -1;return stops.get(stopIndex(d)).distance-stops.get(stopIndex(s)).distance;} }
class Booking { int id,passengerId,trainNumber,source,destination,seatId; String pnr,paymentMethod,status; BigDecimal amount; Booking(int id,int passengerId,int trainNumber,int source,int destination,int seatId,String pnr,BigDecimal amount,String paymentMethod,String status){this.id=id;this.passengerId=passengerId;this.trainNumber=trainNumber;this.source=source;this.destination=destination;this.seatId=seatId;this.pnr=pnr;this.amount=amount;this.paymentMethod=paymentMethod;this.status=status;} }
class WaitingRequest { int id,passengerId,trainNumber,source,destination; WaitingRequest(int id,int passengerId,int trainNumber,int source,int destination){this.id=id;this.passengerId=passengerId;this.trainNumber=trainNumber;this.source=source;this.destination=destination;} }
class Graph { private final Map<Integer,List<Edge>> g=new HashMap<>(); void addEdge(int a,int b,int w){g.computeIfAbsent(a,k->new ArrayList<>()).add(new Edge(b,w));g.computeIfAbsent(b,k->new ArrayList<>()).add(new Edge(a,w));} Map<Integer,Integer>dijkstra(int src){Map<Integer,Integer>d=new HashMap<>();for(int v:g.keySet())d.put(v,Integer.MAX_VALUE);d.put(src,0);PriorityQueue<Node>pq=new PriorityQueue<>(Comparator.comparingInt(n->n.dist));pq.offer(new Node(src,0));while(!pq.isEmpty()){Node n=pq.poll();if(n.dist!=d.getOrDefault(n.v,Integer.MAX_VALUE))continue;for(Edge e:g.getOrDefault(n.v,List.of())){int nd=n.dist+e.w;if(nd<d.getOrDefault(e.to,Integer.MAX_VALUE)){d.put(e.to,nd);pq.offer(new Node(e.to,nd));}}}return d;} }
class Edge { int to,w; Edge(int to,int w){this.to=to;this.w=w;} }
class Node { int v,dist; Node(int v,int dist){this.v=v;this.dist=dist;} }
